// Code generated by go:generate; DO NOT EDIT.

// Generated with command: go generate
// (from the project root)

package modules

import (
	_ "github.com/GoMudEngine/GoMud/modules/archetype"
	_ "github.com/GoMudEngine/GoMud/modules/camping"
	_ "github.com/GoMudEngine/GoMud/modules/cleanup"
	_ "github.com/GoMudEngine/GoMud/modules/company"
	_ "github.com/GoMudEngine/GoMud/modules/death"
	_ "github.com/GoMudEngine/GoMud/modules/encumbrance"
	_ "github.com/GoMudEngine/GoMud/modules/expedition"
	_ "github.com/GoMudEngine/GoMud/modules/exposure"
	_ "github.com/GoMudEngine/GoMud/modules/follow"
	_ "github.com/GoMudEngine/GoMud/modules/gmcp"
	_ "github.com/GoMudEngine/GoMud/modules/light"
	_ "github.com/GoMudEngine/GoMud/modules/market"
	_ "github.com/GoMudEngine/GoMud/modules/mount"
	_ "github.com/GoMudEngine/GoMud/modules/standing"
	_ "github.com/GoMudEngine/GoMud/modules/survival"
	_ "github.com/GoMudEngine/GoMud/modules/walking"
	_ "github.com/GoMudEngine/GoMud/modules/weather"
	_ "github.com/GoMudEngine/GoMud/modules/webhelp"
)
